# Generated by Django 5.0.7 on 2024-10-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FACULTYAPP', '0002_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='course',
            field=models.CharField(choices=[('AOOP', 'advance object_orirnted programming'), ('PFSD', 'python full stack deveplopment')], max_length=50),
        ),
    ]
